# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
development:
  CLIENT_ID: "00c52198590b0c630f58"
  CLIENT_SECRET: "e8cc7e2c2f7a18e71878d75f86a6ca930499303f"
  CALLBACK_URL: "http://localhost:3000/auth/github/callback"
production:
  CLIENT_ID: "ff29bb6afd8f205523e3"
  CLIENT_SECRET: "e709e6fcba574416d49fa81bfafea4df9ea70944"
  CALLBACK_URL: "http://localhost:3000/auth/github/callback"
